### ISSUE TITLE
Make unsafe opcodes fail rather than crash when profiling 

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glulxe#10]
For @restore and @restoreundo at least it should be very easy to make them fail rather than crash when profiling. For @throw and @restart it would be harder because they don't store a result. Perhaps they could get converted into @quit so that the profile would at least finish? 

If you don't mind waiting a little, I'd be interested in brushing up on my C and submitting a pull request for this.

**Comment by erkyrath** [comment]
I agree about @restore and @restoreundo. It would be better to write out the profile data on fatalerror.

Is this coming up testing? All of my profiling tests have involved piping in a simple sequence of commands, and I just avoid including UNDO.

**Comment by curiousdannii** [comment]
We run into trouble with Counterfeit Monkey because Ultra Undo calls @restoreundo to test whether it works, and Startup Precomputation calls @restore to load a memory snapshot. Currently we have to comment things out to make a profiling build, with this we could just use a normal one.

**Comment by curiousdannii** [comment]
I've submitted a pull request that makes the four opcodes safer. You're right that it would be best to write out the profile data on every fatal error, but that's beyond me sorry.

**Comment by erkyrath** [comment]
I have merged in the `@restore/@restoreundo` parts of your patch. Thanks!

I think the changes on `@throw/@restart` are a bit too intrusive for no benefit. I take it that the CM testing doesn't trip over those. A partial profile isn't what anyone wants anyway.

As for `@saveundo` and `@save`, we see from CM that those can take significant time! We *want* to profile them.

**Comment by curiousdannii** [comment]
Sounds good.
