### ISSUE TITLE
Turn on SERIALIZE_CACHE_RAM

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/glulxe#12]
The speed difference becomes meaningful for the `@saveundo` operation of very large games. (E.g. Counterfeit Money, 420Mb RAM.)

Nobody's looked at that code in a while. Make sure it's clean, doesn't leak, is compatible with heap-code, etc.

**Comment by curiousdannii** [comment]
420Mb is a typo, surely? Or when it's running is that how much the heap expands to?

**Comment by erkyrath** [comment]
Yes, sorry, typo. That's 4.20 Mb, as noted in http://www.intfiction.org/forum/viewtopic.php?f=19&t=20387. 

The heap does not expand in the first couple of moves -- I didn't test farther than that.
