### ISSUE TITLE
Extend option to let write-to-zero pass

### ISSUE THREAD

**Issue by DavidKinder** [erkyrath/glulxe#13]
As noted in the thread http://www.intfiction.org/forum/viewtopic.php?f=38&t=3414#p117731 at least one Superglus game still doesn't run, even with TOLERATE_SUPERGLUS_BUG defined.

For the game linked to in the forum post, the problem is that this time it is the @copy opcode that tries to write to 0. Changing the code for op_copy in execute loop() to the following seems to allow the game to run:
```c
      case op_copy:
        value = inst[0].value;
#ifdef TOLERATE_SUPERGLUS_BUG
        if (inst[1].desttype == 1 && inst[1].value == 0)
            inst[1].desttype = 0;
#endif /* TOLERATE_SUPERGLUS_BUG */
        store_operand(inst[1].desttype, inst[1].value, value);
        break;
```

**Comment by erkyrath** [comment]
Done.

**Comment by Utodev** [comment]
Thanks guys for the patch.
