### ISSUE TITLE
--undo should accept a value of zero

### ISSUE THREAD

**Issue by DavidGriffith** [erkyrath/glulxe#24]
Shouldn't it be possible for the `--undo` flag to accept a value of zero so that undo functionality is disabled?

**Comment by erkyrath** [comment]
It's possible, but is it worth bothering with?

In theory a game could behave differently if undo is disabled, but it hasn't come up.

**Comment by DavidGriffith** [comment]
I came up with this while testing a solution to a problem with the Inform6 Standard Library offering UNDO after death when the interpreter might not support that.  Frotz has always reported that it doesn't support UNDO if zero undo slots are specified, so I thought perhaps it would be useful here too.  I'll submit a pull request in a couple days as the change for Glulxe is quite simple.

**Comment by erkyrath** [comment]
Done.
