### ISSUE TITLE
Invalid shift base with Mem4()

### ISSUE THREAD

**Issue by angstsmurf** [erkyrath/glulxe#29]
When running Glulxe with Undefined Behavior Sanitizer on, I get UB warnings such as
```
Left shift of 255 by 24 places cannot be represented in type 'int'
```
at 
https://github.com/erkyrath/glulxe/blob/3b778cfd86e157cbd2bea5723a1f0ef57fb58581/operand.c#L453
and other places where the MEM4() macro is used.

That error message makes no sense to me, as all the involved types are unsigned (glui32), so it might just be a clang bug. Xcode 14.2 on a M1 MacBook.

**Comment by angstsmurf** [comment]
It is possible that you will get the same warnings by compiling with `-fsanitize=undefined` on the command line, but I haven't tried it.

**Comment by erkyrath** [comment]
Thanks.

**Comment by erkyrath** [comment]
I think this is fixed now.

(There were a few other unsigned-math complaints as well.)

While I was at it, I ran inform6 under the same clang option and fixed some warnings there too. So thanks. `:)`
