### ISSUE TITLE
Signaling NaNs in Glulx

### ISSUE THREAD

**Issue by ptomato** [erkyrath/glulxe#31]
There's a [test failure](https://github.com/erkyrath/glk-dev/blob/dae6f7bc77d5f5b414a4bf389e7c8f0fb07b8d73/unittests/glulxercise.inf#L9235) in Glulxercise with Glulxe linked to somewhat recent versions of Glibc, that I've been unable to track down for a long time. The four tests for [edge cases](https://eblong.com/zarf/glulx/Glulx-Spec.html#opcodes_float) of `@pow` having to do with NaN (`pow(1, NaN); pow(1, -NaN); pow(NaN, 0); pow(-NaN, 0)`) all fail because the `@pow` operation returns another NaN, which it's not supposed to.

I finally tracked it down to the definition of the NaNs used:
```
Constant M_NAN  = $7F800001; ! one of many NaN values
Constant M_NNAN = $FF800001; ! another, with a sign bit
```
These are 'signalling NaNs', because the most significant bit of the mantissa is 0. 'Quiet NaNs' would have a 1 bit there, e.g. `$7FC00001`. Signalling NaNs were added to the IEEE floating point standard much later so they're not very well known, but C compilers and standard libraries may treat them differently than quiet NaNs. Compilers generally have switches that can be used to turn the behaviour of signalling NaNs back into quiet NaNs. In this case, I was running into [this code](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/ieee754/flt-32/e_powf.c;h=52afe0ae431448be469e7ab9c944ec766af5b21a;hb=HEAD#l163) in Glibc, which special-cases `powf(1, NaN)` to return NaN if the input NaN is signalling, regardless of what the C compiler does with signalling NaNs.

So, the fix is to not trust the platform's `powf()` function (and probably `pow()` as well) and compile Glulxe with `-DFLOAT_COMPILE_SAFER_POWF` on Linux. I'm assuming we don't want to include the signalling NaN behaviour in the Glulx specification. It's too esoteric and is unlikely to be useful.

However, it might be nice to make Glulxe more robust against this little-known C standard library quirk on some platforms. I can think of a few possible actions to take:

1. Change the `M_NAN` and `M_NNAN` constants in `glulxercise.inf` to be quiet NaN bit patterns. This is essentially saying "we don't care, it's harmless if your stdlib has this quirk, but at least your tests won't fail."
2. Make it more obvious what the problem might be if `glulxercise.inf` fails: for example, test explicitly with both quiet and signaling NaNs so it's clear if one fails and the other doesn't, and add a line in `glulxercise.inf` suggesting compiling Glulxe with `-DFLOAT_COMPILE_SAFER_POWF` if the floatexp test fails.
3. Change Glulxe to just always use the safer `powf()` wrapper, and never use the platform's `powf()` directly; add a similar wrapper for `pow()`.
4. Change Glulxe to turn signalling NaNs into quiet NaNs whenever encoding or decoding them for a float or double operation. As far as I can tell, it's possible to do this and still be conformant with the Glulx spec.

What do you think?

**Comment by curiousdannii** [comment]
Are the tests not using the `jisnan` opcode, or is the opcode not working for these NaNs?

**Comment by ptomato** [comment]
I'm pretty sure `jisnan` is working correctly. The problem is in [executing the `pow` opcode](https://github.com/erkyrath/glulxe/blob/master/exec.c#L924-L927). We decode the operands into 32-bit floats in C, and one of them is a signalling NaN which causes the call to [`glulx_powf()` and the platform's `powf()`](https://github.com/erkyrath/glulxe/blob/master/osdepend.c#L237-L240) to misbehave.

**Comment by curiousdannii** [comment]
Oh, I misunderstood the issue.

So the question is whether the defaults should be changed to be safer, or perhaps whether to make NaNs conform within Glulxe.

`glulx_powf` is a pretty cheap wrapper around `powf`, so it wouldn't hurt to always use it. But it's also quite easy to enable if needed. Option 4 would almost certainly be a much worse performance hit.

**Comment by erkyrath** [comment]
Using the glulx_powf() wrapper, and adding glulx_pow(), seems easiest. Done.
