### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by rebroad** [erkyrath/glulxe#7]
I've just downloaded the latest master and both "make" and "make gluxe" are failing. The error given is:-

Makefile:36: ../cheapglk/Make.cheapglk: No such file or directory
make: *** No rule to make target '../cheapglk/Make.cheapglk'. Stop.

**Comment by erkyrath** [comment]
The Makefile expects you to have already compiled cheapglk (https://github.com/erkyrath/cheapglk) in a parallel directory. See the README. Sorry, I know it's not a standard automake setup.
