### ISSUE TITLE
cheapglk hangs on graphic windows

### ISSUE THREAD

**Issue by andrewschultz** [erkyrath/glulxe#8]
This test was run on 6G60.

glulxe -q output.ulx hangs the interpreter.

```
"grfx" by Andrew

room 1 is a room.

include Glimmr Drawing Commands by Erik Temple.

include Glimmr Bitmap Font by Erik Temple.

The graphics-window is a graphics g-window spawned by the main-window. the position is g-placeabove. The scale method of the graphics-window is g-proportional. The measurement of the graphics-window is 10.

when play begins:
	open up the graphics-window;

```

(I used "say 1."; and "say 2."; to verify that the open up the graphics-window command did freeze glulxe.)

If there is a quick fix, great, but I have a cheap work-around.

The binary is here: https://www.dropbox.com/s/99wsccs53yvjwy9/grfx.ulx?dl=0

**Comment by erkyrath** [comment]
This sounds like a bug in the window extensions used by Glimmr. I note that grfx.ulx doesn't work in Quixe/Lectrote either.

If graphics are not available, glk_window_open returns 0 if you try to open a graphics window. The game is either failing to detect this, or is getting confused and not setting up input correctly in the main window.

**Comment by erkyrath** [comment]
Or -- I'm not familiar with how Glimmr works under the surface. It's possible that it's the game's responsibility to check whether graphics are available before saying "open up the graphics-window".

In any case, I am sure that the game is getting into a loop where it is not calling glk_select().

**Comment by curiousdannii** [comment]
Glimmr just includes Flexible Windows for opening windows, and even really old versions of FW checked whether the window was successfully opened.

**Comment by erkyrath** [comment]
I did a super-simple test: (in 6G60)

    Include Flexible Windows by Jon Ingold.
    The Kitchen is a room.

This by itself hangs in cheapglk. Some probing led me to the "calibrate windows" phrase, which has the lines

	while there is a g-required g-unpresent next-step g-windows (called H):
		carry out the constructing activity with H;

The status window is g-required but cannot be opened in cheapglk, so this loops forever. Boom.

**Comment by andrewschultz** [comment]
Thanks to both of you for looking into this! Now that I'm reading this, I see how I could've debugged more to see whether it was the extension or executable. I thought it was good enough to see that the app worked ok in the IDE but not cheapglulxe, but I see a few more steps.

This looks like it would not be hard to fix in the extension with some poking, so I am more than okay with closing this issue. I thought I'd leave it open if you wanted to point me to any other things to check before opening an issue in the future. glulxe has been very good for unit testing so far & so I may be using it rather heavily.

**Comment by erkyrath** [comment]
I will close this, but it could be opened as a Flexible Windows bug. (But I haven't checked to see if later updates have the same problem.)

**Comment by curiousdannii** [comment]
Ah yep that's easy to fix. Change the body of the window could not be created rule to

	if the ref-number of win is zero:
		now win is g-unpresent;
		now win is g-unrequired;
		rule fails;
